In [1]:
import pandas as pd
import numpy as np

from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error

import matplotlib.pyplot as plt

import mlflow

In [2]:
prophet = pd.read_csv("../Data/prophet_forecast.csv")

prophet.head()

,ds,trend,yhat_lower,yhat_upper,trend_lower,trend_upper,additive_terms,additive_terms_lower,additive_terms_upper,weekly,weekly_lower,weekly_upper,yearly,yearly_lower,yearly_upper,multiplicative_terms,multiplicative_terms_lower,multiplicative_terms_upper,yhat
0,2009-12-01 07:45:00,294.273828,-32.126904,627.089103,294.273828,294.273828,7.359213,7.359213,7.359213,10.015179,10.015179,10.015179,-2.655966,-2.655966,-2.655966,0.0,0.0,0.0,301.633042
1,2009-12-01 07:46:00,294.273739,-27.436232,654.899851,294.273739,294.273739,7.351785,7.351785,7.351785,10.008802,10.008802,10.008802,-2.657017,-2.657017,-2.657017,0.0,0.0,0.0,301.625525
2,2009-12-01 09:06:00,294.266631,-31.353317,637.845096,294.266631,294.266631,6.798494,6.798494,6.798494,9.539599,9.539599,9.539599,-2.741105,-2.741105,-2.741105,0.0,0.0,0.0,301.065125
3,2009-12-01 09:08:00,294.266454,-39.965161,658.500306,294.266454,294.266454,6.785685,6.785685,6.785685,9.528892,9.528892,9.528892,-2.743207,-2.743207,-2.743207,0.0,0.0,0.0,301.052139
4,2009-12-01 09:28:00,294.264677,-46.504030,636.332678,294.264677,294.264677,6.660290,6.660290,6.660290,9.424506,9.424506,9.424506,-2.764216,-2.764216,-2.764216,0.0,0.0,0.0,300.924967

In [3]:
lstm = pd.read_csv("../Data/lstm_forecast.csv")

lstm.head()

   Day  ForecastSales
0    1     255.025906
1    2     255.283878
2    3     255.428889
3    4     255.538403
4    5     255.617276

In [4]:
lstm.columns = [
    "Day",
    "LSTM_Prediction"
]

In [5]:
lstm.rename(
    columns={
        "Prediction":"LSTM_Prediction"
    },
    inplace=True
)

In [6]:
hybrid = prophet.tail(len(lstm)).copy()

hybrid.reset_index(
    drop=True,
    inplace=True
)

lstm.reset_index(
    drop=True,
    inplace=True
)

hybrid["LSTM"] = lstm["LSTM_Prediction"]

In [7]:
hybrid["HybridForecast"] = (

    hybrid["yhat"] +

    hybrid["LSTM"]

)/2

In [11]:
hybrid.to_csv(

    "hybrid_forecast.csv",

    index=False

)

print("Hybrid Forecast Saved")

Hybrid Forecast Saved